name: test

on:
  push:
    branches:
      - wip/testing

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: x64

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run Python Tests
        run: python -m unittest discover

  build_windows:
    runs-on: windows-latest
    needs: [build_ubuntu] # Ensures build_windows runs after build_ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: x64

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run Python Tests
        run: python -m unittest discover
